### ISSUE TITLE
winlogbeat started several times by graylog_collector_sidecar

### ISSUE THREAD

**Issue by csmpg** [Graylog2/collector-sidecar#116]
### Problem description
winlogbeat  has a weird behaviour if ran by graylog_collector_sidecar
multiple starts and stop  if sidecar is ran as a process or as a service
### Steps to reproduce the problem

I have installed  Graylog Appliance v2.1 (1st machine) ,
 i have installed   graylog_collector_sidecar.exe  on a Windows 2008 R2 (2nd
 machine), i have not installed winlogbeat.exe as it is embedded into the
c:\programfiles\graylog\collector_sidecar directory

communication is established between both machines

 I have configured  an input and output on a configuration linked to the
Windows and iis tags (tags found in graylog_collector_sidecar.yml file)

Graylogserver can see this collector

When i run graylog_collector_sidecar.exe  in a cmd  for debug purpose, i can
see that winlogbeat keeps on starting, then crashing with those logs :

msg="[Winlogbeat] Starting <exec driver>"
msg="[Winlogbeat] Configuration change detected, rewriting configuration
file"
msg="[Winlogbeat] Stopping"
msg="[Winlogbeat] Backend crashed, trying to restart 1/3"
  ....
msg="[Winlogbeat] Unable to start collector after 3 tries, giving up"
msg="[Winlogbeat] Starting <exec driver>"

On Graylog Appliance :
 - status of this collector  loops between Running and Failing

### Environment

* Sidecar Version: 0.1.0 (3880fd) [go1.7.4/amd64]
* Graylog Version: Graylog Appliance v2.1
* Operating System: Windows Server 2008 R2 Standard 6.1 Service Pack 1 Build 7601
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment]
Just tried 0.1.0-beta.2 on a fresh Windows 2012R2 box and couldn't reproduce the problem. After starting the Sidecar it tries to spin up Filebeat and Winlogbeat which fails because of an empty configuration. After 3 retries it gives up and no processes are left behind. After adding a valid configuration all works as expected.

Is this a permanent error, is still happening after cleaning out the processes or a reboot?

```
PS C:\Program Files\Graylog\collector-sidecar> .\Graylog-collector-sidecar.exe
time="2016-12-15T05:59:52-08:00" level=info msg="collector-id file doesn't exist, generating a new one"
time="2016-12-15T05:59:52-08:00" level=info msg="Using collector-id: 6b86afa4-a66b-4bdc-80d0-e21995f0e0ef"
time="2016-12-15T05:59:52-08:00" level=info msg="Fetching configurations tagged by: [windows iis]"
time="2016-12-15T05:59:52-08:00" level=info msg="Starting signal distributor"
time="2016-12-15T05:59:52-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2016-12-15T05:59:52-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2016-12-15T05:59:52-08:00" level=error msg="[filebeat] Backend crashed, trying to restart 1/3"
time="2016-12-15T05:59:52-08:00" level=info msg="[filebeat] Stopping"
time="2016-12-15T05:59:52-08:00" level=error msg="[winlogbeat] Backend crashed, trying to restart 1/3"
time="2016-12-15T05:59:52-08:00" level=info msg="[winlogbeat] Stopping"
time="2016-12-15T05:59:54-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2016-12-15T05:59:54-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2016-12-15T05:59:55-08:00" level=error msg="[filebeat] Backend crashed, trying to restart 2/3"
time="2016-12-15T05:59:55-08:00" level=info msg="[filebeat] Stopping"
time="2016-12-15T05:59:55-08:00" level=error msg="[winlogbeat] Backend crashed, trying to restart 2/3"
time="2016-12-15T05:59:55-08:00" level=info msg="[winlogbeat] Stopping"
time="2016-12-15T05:59:57-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2016-12-15T05:59:57-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2016-12-15T05:59:57-08:00" level=error msg="[winlogbeat] Backend crashed, trying to restart 3/3"
time="2016-12-15T05:59:57-08:00" level=info msg="[winlogbeat] Stopping"
time="2016-12-15T05:59:57-08:00" level=error msg="[filebeat] Backend crashed, trying to restart 3/3"
time="2016-12-15T05:59:57-08:00" level=info msg="[filebeat] Stopping"
time="2016-12-15T05:59:59-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2016-12-15T05:59:59-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2016-12-15T05:59:59-08:00" level=error msg="[winlogbeat] Unable to start collector after 3 tries, giving up
time="2016-12-15T05:59:59-08:00" level=error msg="[filebeat] Unable to start collector after 3 tries, giving up!"
```

**Comment by llucenic** [comment]
It seems I am having a similar problem in my deployment, however, with Filebeat. Once I start the service (running under Windows Server 2012), I keep getting new and new filebeat.exe processes at a pace about 70/hour. My configuration only checks in about 10 files, so I do not understand for what reason are there so many harvesters running in the background in the first place. Is this suspicious behaviour or may I have configured something incorrectly?

**Comment by mariussturm** [comment]
@llucenic no this is a bug, please use the latest stable 0.9.0 for now. I am working on the next beta.

**Comment by llucenic** [comment]
Thank you for the reply and workaround, @mariussturm.

**Comment by mariussturm** [comment]
This should be fixed in 0.1.0-beta.3, please test again.

**Comment by kwisatz** [comment]
@mariussturm I upgraded to beta 3 and am still seeing this (although I'm not sure my issue is really OPs issue since mine is happening with filebeat on linux).

```
Jan 13 19:18:38 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:18:38+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:18:40 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:18:40+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:18:40 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:18:40+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:19:10 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:10+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:19:10 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:10+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:19:10 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:10+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:19:10 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:10+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:19:12 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:12+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:19:12 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:12+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:19:42 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:42+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:19:42 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:42+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:19:42 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:42+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:19:42 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:42+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:19:44 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:19:44+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:19:44 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:19:44+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:20:14 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:20:14+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:20:14 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:20:14+01:00" level=info msg="[filebeat] Configuration change detected, rewriting configuration file."
Jan 13 19:20:14 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:20:14+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:20:14 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:20:14+01:00" level=info msg="[filebeat] Stopping"
Jan 13 19:20:16 database1 /usr/bin/graylog-collector-sidecar[2666]: time="2017-01-13T19:20:16+01:00" level=info msg="[filebeat] Starting (exec driver)"
Jan 13 19:20:16 database1 graylog-collector-sidecar[2666]: time="2017-01-13T19:20:16+01:00" level=info msg="[filebeat] Starting (exec driver)"
[…]
```

Would you like me to open a different issue for this or is it related?

**Comment by mariussturm** [comment]
@kwisatz yeah, creating a new ticket would be easier. We need the configuration you made in the web ui to reproduce this. Thank you!
