### ISSUE TITLE
collector-sidecar unable to start winlogbeat

### ISSUE THREAD

**Issue by achermes** [Graylog2/collector-sidecar#90]
### Problem description

The graylog collector sidecar is not able to start winlogbeat successfully - winlogbeat exits with an error about not being able to find the config file.

I successfully installed the graylog-collector sidecar and was able to pull down a very basic winlogbeat configuration, which was promptly placed at generated/winlogbeat.yml. So far, so good. However, when I try to run the sidecar, winlogbeat exits with an error about not being able to find the configuration file:

```
Loading config file error: Failed to read "C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml": open "C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml": The filename, directory name, or volume label syntax is incorrect.. Exiting.
```

The error message is mistifying as the indicated path _does_ exist! Indeed, if I run winlogbeat from the command console as follows, it completes without complaint:

```
C:\Program Files\graylog\collector-sidecar>winlogbeat.exe -c "C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml" -configtest
```
### Steps to reproduce the problem
1. Install graylog-collector-sidecar on the remote machine from which windows events logs should be collected
2. Follow the [step by step guide|http://docs.graylog.org/en/latest/pages/collector_sidecar.html#step-by-step-guide], configuring winlogbeat (with default configuration) instead of filebeat
3. Attempt to start the collector sidecar service on the remote machine.
#### collector-sidecar.yml

```
server_url: <redacted server url>/api 
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: graylog-collector-sidecar
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
log_path: C:\Program Files\graylog\collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags: [windows, iis]
backends:
    - name: nxlog
      enabled: false
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: 'C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml'
    - name: filebeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: 'C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml'
```
#### generated/winlogbeat.yml

```
output:
  logstash:
    hosts:
    - <redacted>:5044
shipper:
  tags:
  - windows
  - iis
winlogbeat:
  event_logs:
  - name: Application
  - name: System
  - name: Security
```
### Environment
- Sidecar Version: 0.1.0-alpha.2
- Graylog Version: v2.1.1+01d50e5
- Operating System: Windows Server 2012 R2 64-bit
- Elasticsearch Version:
- MongoDB Version:

**Comment by mariussturm** [comment]
This should be fixed in 0.1.0-beta.1

**Comment by lbull** [comment]
@mariussturm, I'm still having this problem even after fixing it (0.1.0-beta.1).

**Config**

**collector-sidecar.yml**

```
server_url: http://mygraylogserver:9000/api 
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: graylog-collector-sidecar-kk
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
log_path: C:\Program Files\graylog\collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags: [windows]
backends:
    - name: nxlog
      enabled: false
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml
    - name: filebeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml
```

**generated/winlogbeat.yml**

```
output:
  logstash:
    hosts:
    - mygraylogserver:5044
shipper:
  tags:
  - windows
winlogbeat:
  event_logs:
  - name: Application
  - name: System
  - name: Security
```

**generated/filebeat.yml**

```
filebeat:
  prospectors: []

```

**filebeat_stderr.log**

> ...
Loading config file error: Failed to read C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml: open C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml: The system cannot find the file specified.. Exiting

**winlogbeat_stderr.log**
> 
Loading config file error: Failed to read C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml: open C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml: The system cannot find the file specified.. Exiting.

**Environment**

- Sidecar Version: 0.1.0-beta.1
- Graylog Version: v2.1.1+01d50e5
- Operating System: Windows 7
- Elasticsearch Version:
- MongoDB Version:

**Comment by mariussturm** [comment]
@lbull sorry, can't reproduce the error with 0.1.0-beta.1. I cut&paste your configuration and both collectors worked fine. Did you check that you actually upgrade the installation? Maybe uninstall, remove \Program Files\graylog and re-install the Sidecar helps. Also bear in mind that the _stderr files are not flushed on restart. So the errors could be old entries too.
